import {CamoAuthorizationExecutionResult,CamoServerAuthorizationContext} from "../domain/authorization_types";
import {CamoMessagePolicyActivationGate,CamoServerAuthorizer} from "./authorized_message_policy_service";
import {CamoMessagePolicyV2LifecycleService} from "./message_policy_v2_lifecycle_service";
const deny=(reasonCode:string):CamoAuthorizationExecutionResult=>Object.freeze({authorized:false,reasonCode});
export class AuthorizedMessagePolicyV2Service implements CamoServerAuthorizer{
 constructor(private readonly authorizer:CamoServerAuthorizer,private readonly lifecycle:CamoMessagePolicyV2LifecycleService,private readonly gate:CamoMessagePolicyActivationGate){}
 async authorize(c:CamoServerAuthorizationContext):Promise<CamoAuthorizationExecutionResult>{if(!this.gate.isMessagePolicyMutationEnabled())return deny("server_message_policy_mutation_not_activated");const pairId=c.pairId?.trim(),messageId=c.messageId?.trim();if(!pairId||!messageId)return deny("server_message_policy_binding_invalid");
  if(c.operationType==="encode"){if(c.messageValidity===undefined||c.oneTimeView!==false)return deny("server_encode_message_policy_invalid");try{await this.lifecycle.reserve({messageId,pairId,senderUserId:c.userId,senderDeviceId:c.deviceId,operationId:c.operationId,validity:c.messageValidity});}catch{return deny("server_message_policy_reservation_denied");}let result:CamoAuthorizationExecutionResult;try{result=await this.authorizer.authorize(c);}catch{try{await this.lifecycle.block(messageId,"server_authorizer_failed");}catch{}return deny("server_authorizer_failed");}if(!result.authorized||result.signedResponse===undefined){try{await this.lifecycle.block(messageId,result.reasonCode);}catch{}return result;}try{await this.lifecycle.activate(messageId,result.signedResponse.authorizationId,result.signedResponse.signingKeyId);return result;}catch{try{await this.lifecycle.block(messageId,"activation_failed");}catch{}return deny("server_message_policy_activation_denied");}}
  if(c.operationType==="decode"){const result=await this.authorizer.authorize(c);if(!result.authorized||result.signedResponse===undefined)return result;try{await this.lifecycle.consume(messageId);return result;}catch{return deny("server_decode_reservation_denied");}}
  return deny("server_message_policy_operation_invalid");}}
