// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwAFCOoEe0HeSFn3Zlu05KEgIPT844BAc',
    appId: '1:224858679064:web:5a838b5b5d765dea0d206d',
    messagingSenderId: '224858679064',
    projectId: 'camo-b3cab',
    authDomain: 'camo-b3cab.firebaseapp.com',
    storageBucket: 'camo-b3cab.firebasestorage.app',
    measurementId: 'G-NNYXJ7E2F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDsGwq6daNZv0ispDse9yEfJvD2cl_vv4',
    appId: '1:224858679064:android:33fd2511500ea0f50d206d',
    messagingSenderId: '224858679064',
    projectId: 'camo-b3cab',
    storageBucket: 'camo-b3cab.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkZ5xCmFPmD7flvQ_KP4EvPnSiUMKssXE',
    appId: '1:224858679064:ios:31d70ca6d9a8ae3e0d206d',
    messagingSenderId: '224858679064',
    projectId: 'camo-b3cab',
    storageBucket: 'camo-b3cab.firebasestorage.app',
    iosBundleId: 'com.example.camo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkZ5xCmFPmD7flvQ_KP4EvPnSiUMKssXE',
    appId: '1:224858679064:ios:31d70ca6d9a8ae3e0d206d',
    messagingSenderId: '224858679064',
    projectId: 'camo-b3cab',
    storageBucket: 'camo-b3cab.firebasestorage.app',
    iosBundleId: 'com.example.camo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwAFCOoEe0HeSFn3Zlu05KEgIPT844BAc',
    appId: '1:224858679064:web:59b5b688136853490d206d',
    messagingSenderId: '224858679064',
    projectId: 'camo-b3cab',
    authDomain: 'camo-b3cab.firebaseapp.com',
    storageBucket: 'camo-b3cab.firebasestorage.app',
    measurementId: 'G-CBJY1J0VBZ',
  );
}
